// <auto-generated />
using GenericFilter;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GenericFilter.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240821045122_SeedMoreRecords")]
    partial class SeedMoreRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GenericFilter.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Home Appliances"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Toys"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Beauty"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Garden"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Office Supplies"
                        });
                });

            modelBuilder.Entity("GenericFilter.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Smartphone",
                            Price = 699.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Laptop",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Headphones",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "Smartwatch",
                            Price = 249.99m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Name = "Bluetooth Speaker",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Name = "E-Book Reader",
                            Price = 129.99m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Name = "Science Fiction Novel",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Name = "Cookbook",
                            Price = 24.99m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Name = "Self-Help Book",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Name = "Historical Fiction",
                            Price = 21.99m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Name = "T-Shirt",
                            Price = 15.99m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Name = "Jeans",
                            Price = 39.99m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Name = "Jacket",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Name = "Sweater",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Name = "Dress",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            Name = "Air Conditioner",
                            Price = 299.99m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            Name = "Microwave Oven",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            Name = "Washing Machine",
                            Price = 499.99m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Name = "Refrigerator",
                            Price = 799.99m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Name = "Dishwasher",
                            Price = 399.99m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 5,
                            Name = "Building Blocks",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 5,
                            Name = "Dollhouse",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            Name = "Action Figures",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            Name = "Toy Car",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            Name = "Board Game",
                            Price = 24.99m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 6,
                            Name = "Basketball",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 6,
                            Name = "Tennis Racket",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 6,
                            Name = "Soccer Ball",
                            Price = 22.99m
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 6,
                            Name = "Golf Club",
                            Price = 119.99m
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 6,
                            Name = "Yoga Mat",
                            Price = 39.99m
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 7,
                            Name = "Face Cream",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 7,
                            Name = "Shampoo",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 7,
                            Name = "Lipstick",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 7,
                            Name = "Perfume",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 7,
                            Name = "Nail Polish",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 8,
                            Name = "Car Battery",
                            Price = 129.99m
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 8,
                            Name = "Engine Oil",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 8,
                            Name = "Tire",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 8,
                            Name = "Car Wash Kit",
                            Price = 24.99m
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 8,
                            Name = "GPS Navigation System",
                            Price = 149.99m
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 9,
                            Name = "Garden Tools Set",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 9,
                            Name = "Flower Pots",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 9,
                            Name = "Lawn Mower",
                            Price = 299.99m
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 9,
                            Name = "Outdoor Furniture",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 9,
                            Name = "Watering Can",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 10,
                            Name = "Desk Chair",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 10,
                            Name = "Office Desk",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 10,
                            Name = "Printer",
                            Price = 149.99m
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 10,
                            Name = "Notebooks",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 10,
                            Name = "Desk Lamp",
                            Price = 29.99m
                        });
                });

            modelBuilder.Entity("GenericFilter.Product", b =>
                {
                    b.HasOne("GenericFilter.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GenericFilter.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
